@startuml
'https://plantuml.com/class-diagram

abstract  lineToList
interface ListofNames
interface print

lineToList <|-- readFile
List <|-- lineToList
ListofNames <|- list
sort <|- ListofNames
print <|- sort


class readFile {
file
}

class sort {
listofNames
}

enum InputContent {
Names
}

@enduml