@startuml
'https://plantuml.com/class-diagram

abstract  userInput


createFile <|-- userInput
createHTLM <|-- createFile
createjs <|-- createHTLM
createcss <|- createHTLM

output <|-- createjs
output <|-- createcss
output <|-- createHTLM

enum InputContent {
WebsiteName
}

@enduml