@startuml
'https://plantuml.com/class-diagram

readLine <|-- readFile
getWord <|- readLine
wordCount <|-- getWord
readLine <|-- wordCount

sortCount <|-- readLine

print <|-- sortCount



enum InputContent {
word
}

@enduml